FoveaCentral/google_maps_geocoder

- lib/google_maps_geocoder.rb
- spec/lib/google_maps_geocoder_spec.rb
Google allows to use API key with Geocoding functionality and it has some benefits, for example you can see how many queries you've don already.
See documentation API key section for more info: https://developers.google.com/maps/documentation/geocoding/intro?hl=en_US
This commit checks, if we have ENV variable named GOOGLE_API_TOKEN and if we do, adds key=your_api_key to request URI to google.
> Add an ability to use API key

- lib/google_maps_geocoder/google_maps_geocoder.rb
- spec/lib/google_maps_geocoder_spec.rb
1. Reduce error classes to `GeocodingError`, which wraps the JSON response.
2. Rename method names, arguments, and constants for clarity and relatedness.
> Simplify error handling

- README.md
- lib/google_maps_geocoder/google_maps_geocoder.rb
- spec/lib/google_maps_geocoder_spec.rb
Closes: #18
Support [`geocoder`'s API](https://github.com/alexreisner/geocoder#custom-result-handling) to facilitate migration.
Add methods for:
1. `#address`
2. `#coordinates`
3. `#country`
4. `#country_code`
5. `#latitude`
6. `#longitude`
7. `#state`
8. `#state_code`
> Support Geocoder's API

- google_maps_geocoder.gemspec
This PR updates the homepage URI to use `https`.
Keep the metadata up-to-date.
1. Edit in-place.
> (chore) gemspec: HTTPS in homepage URL

- .travis.yml
Increase the knowledge we have about how this library runs with latest Ruby.
1. add a 2.7 (an rvm alias)
2. drop unused directive sudo: false
This PR removes the no-longer-used Travis setting `sudo: false`. See [more at the Travis blog](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
> CI: Add Ruby 2.7

- README.md
Updated `README` to reflect the fact that a Google Maps API key is no longer optional.
> doc: updated readme so key isn't optional

- Gemfile
- Rakefile
- google_maps_geocoder.gemspec
- lib/google_maps_geocoder/google_maps_geocoder.rb
- lib/google_maps_geocoder/version.rb
- spec/lib/google_maps_geocoder_spec.rb
- spec/spec_helper.rb
Update to the latest version of Rubocop that has wide Ruby support, 1.8. Build was still using 0.49.
1. Bump rubocop to < 1.9 (because latter requires ruby 2.4 and we want to provide as broad support as possible).
2. Run `bundle ex rubocop -A`.
> Update to Rubocop < 1.9

- README.md
Closes: #30 
Remove Hakiri since integrating Dependabot made it obsolete: ac06707f6f978b1e875ed078ee0d8a55d5df8d4f.
1. Remove badge.
2. Remove webhook.
> doc: removed hakiri badge

- .github/workflows/test.yml
- .simplecov
- google_maps_geocoder.gemspec
- spec/spec_helper.rb
Closes: #42
Fix Coveralls errors.
1. Moved Coveralls call to GitHub workflow (same as [vaccine-notifier](https://github.com/ivanoblomov/vaccine-notifier)).
2. Removed Ruby 2.2, 2.3 due to incompatibilities with `simplecov`. We're still supporting the last five Ruby releases without them.
> fix: moved coveralls to workflow

- .github/workflows/test.yml
- google_maps_geocoder.gemspec
- lib/google_maps_geocoder/google_maps_geocoder.rb
Add rubocop to CI.
1. Run bundle ex rubocop in test.yml.
2. Run `rubocop -A` after [verified failure](https://github.com/ivanoblomov/google_maps_geocoder/runs/2206001541).
3. Disable `Gemspec/RequiredRubyVersion` cop since we don't want to dictate it.
> CI: added rubocop

- google_maps_geocoder.gemspec
- spec/lib/google_maps_geocoder_spec.rb
Fix rubocop warnings.
1. Bumped `rubocop`.
2. Added recommended gems:
1. `rubocop-rake`
2. `rubocop-rspec`
3. `rubocop -A`
> fix: rubocop warnings

- .github/workflows/test.yml
- google_maps_geocoder.gemspec
Fix [`required_ruby_version` failure](https://github.com/ivanoblomov/google_maps_geocoder/runs/4175164372?check_suite_focus=true) in master.
Require the [minimum supported Ruby version](https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-4-10-released/): 2.5.
> conf: require >= ruby 2.4

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Re: #63
Add Developer Certificate of Origin.
1. Adapt CII Best Practices' [DCO](https://github.com/coreinfrastructure/best-practices-badge/blob/main/CONTRIBUTING.md).
2. Add `Signed-off-by` tag to PR template (instead of every commit message).
> CII silver: project oversight

- google_maps_geocoder.gemspec
Closes: n/a
Cleanup, leaner gemspec.
- `test_files` is not used in RubyGems.org, and
- this gem exposes no executables.
1. Inspect the gemspec.
2. No changes need documentation.
> gemspec: Remove unused directives

- .github/workflows/test.yml
Closes: n/a
Cleanup CI configuration for test Workflow.
This PR uses the `bundler-cache` feature of the Ruby-maintained Action `ruby/setup-ruby`.
[See `ruby/setup-ruby` parameters declaration](https://github.com/ruby/setup-ruby/blob/master/action.yml) for more information.
In addition:
- Quote the 3.0 to avoid it turning into "3" when used.
- Name the Job.
- Spell `bundle exec` the same everywhere.
1. Note that the CI configuraiton for tests didn't cache gems.
2. Make the change, documenting the oddities with code comments.
---
On Quoting:
This is a very small change, but which avoids a Float-to-String loss of characters.
An example (not from this project) of what it can look like before this change, in this picture:
Read more details, if you like: …
> CI: use bundler-cache: true in test Workflow

- .github/workflows/test.yml
Closes: #
In order to see changes work/not work, let users run CI.
1. Add CI event pull_request to the `test` Workflow.
> CI: run on Pull Request, too

- Gemfile
- google_maps_geocoder.gemspec
Closes: n/a
This change clarifies the gemspec to be about the runtime dependencies
only.
What tools are used to test and lint the project is not so important to
the reader of the gemspec.
1. Turn the development deps in the gemspec into `gem` lines in the Gemfile.
1. We only ever use Bundler.
2. This clarifies and focuses the gemspec file.
> chore: Move development deps to Gemfile

- .github/workflows/test.yml
Closes: #87
Fix coverage metrics by migrating to Code Climate.
1. Adapt [GitHub's example](https://github.com/marketplace/actions/code-climate-test-reporter).
2. Remove `pull_request` run to avoid [duplication](https://github.com/FoveaCentral/google_maps_geocoder/pull/85).
> conf: code-climate coverage

- .github/workflows/test.yml
- README.md
Closes: #87
Fix coverage metrics by migrating to Code Climate.
1. Adapt [GitHub's example](https://github.com/marketplace/actions/code-climate-test-reporter).
2. Remove `pull_request` run to avoid [duplication](https://github.com/FoveaCentral/google_maps_geocoder/pull/85).
3. Remove Coveralls from workflow and badge from README.
> Cc coverage

- .github/workflows/test.yml
- README.md
Re: #87
Restore Coveralls in case Code Climate's coverage may not generate failures. Both are merely processing results from the save SimpleCov run anyway.
1. Add Coveralls step.
2. Add badge.
3. [Delete and re-add repo](https://coveralls.io/github/FoveaCentral/google_maps_geocoder/settings) in Coveralls to clear any invalid state.
4. Merge to master to confirm results since other branches behave strangely.
> CI: restore Coveralls

- Gemfile
- google_maps_geocoder.gemspec
- lib/google_maps_geocoder/google_maps_geocoder.rb
- spec/spec_helper.rb
Closes: n/a
In order to have an even smaller dependency surface, let's remove the ActiveSupport library.
1. Remove the gem dependency.
2. Replace `ActiveSupport::JSON.decode` with `JSON.parse`.
3. Add `pry` to facilitate debugging.
> refactor: stop using ActiveSupport

- spec/lib/google_maps_geocoder_spec.rb
- spec/spec_helper.rb
Closes: n/a
Silence log output during tests for cleaner test results.
1. Mock `logger` calls before each example.
2. Restore original behavior after.
3. Extract `:silence_logger` argument to silence conditionally (we lose coverage otherwise).
4. Simplify network/API error handling by consolidating logic into `subject`.
> spec: silence output

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- SECURITY.md
- google_maps_geocoder.gemspec
Closes: #69
1. Updated repo links.
These links became outdated because [requiring 2FA](https://bestpractices.coreinfrastructure.org/en/projects/92?criteria_level=2#changecontrol) necessitated moving the repository into an organization.
> doc: repo links

- spec/lib/google_maps_geocoder_spec.rb
Fix failure: ["White House" is expected to be exact match](https://github.com/FoveaCentral/google_maps_geocoder/runs/5491682114?check_suite_focus=true).
Expect partial match instead.
> fix: spec/lib/google_maps_geocoder_spec.rb:18

- .github/FUNDING.yml
- LICENSE.txt
Allow users to sponsor via GitHub.
1. Add username to `FUNDING.yml`.
2. _Unrelated:_ Update license copyright.
> Added GitHub sponsorhip

- spec/lib/google_maps_geocoder_spec.rb
Observe conventions in [RSpec Style Guide](https://rspec.rubystyle.guide) so output reads as full sentences.
1. Add `context` for valid API key.
2. Wrap each method test in a `describe` block.
`rspec --format d` outputs:
```ruby
GoogleMapsGeocoder
#new
with "White House"
is expected to be partial match
is expected not to be exact match
address
is expected to eq "1600 Pennsylvania Avenue Northwest"
is expected to eq "Washington"
is expected to eq "District of Columbia"
is expected to eq "DC"
is expected to eq "20500"
is expected to eq "US"
is expected to eq "United States"
is expected to match /1600 Pennsylvania Avenue NW, Washington, DC 20500, USA/
coordinates
is expected to be within 0.005 of 38.8976633
is expected to be within 0.005 of -77.0365739
Geocoder API
is expected to eq "1600 …
```
> spec: observe RSpec style

- .rubocop.yml
- Gemfile
- google_maps_geocoder.gemspec
- lib/google_maps_geocoder/google_maps_geocoder.rb
- spec/lib/google_maps_geocoder_spec.rb
- spec/spec_helper.rb
Configure installed Rubocop extensions correctly and add `rubocop-performance`.
1. Add `rubocop-performance` to `Gemfile`.
2. Add `rubocop.yml` and require all extensions.
3. Run `rubocop -A`.
4. Fix remaining warnings.
> Enable existing Rubocop extensions; add rubocop-performance

- .github/workflows/test.yml
- Gemfile
- google_maps_geocoder.gemspec
Increase security and compatibility and make the install process less brittle by:
* restricting Ruby to [supported versions](https://endoflife.date/ruby)
* *not* specifying dependency versions
This should also reduce Dependabot noise.
1. Remove unmaintained 3.0 from `test.yml` and update `required_ruby_version`.
2. Remove versions from `Gemfile` and `gemspec`.
3. Delete `Gemfile.lock` and run `bundle install`.
> conf: remove old rubies, dependency versions

- README.md
The gem won't work following the "Installation" steps for Bundler. Correct them.
1. Add a `require` to match the `irb` instructions.
> doc: require in Gemfile

- .github/CODEOWNERS
Address https://github.com/FoveaCentral/google_maps_geocoder/security/code-scanning/1 by adding `CODEOWNERS` to the repo.
1. Declare Olle and Rod as `CODEOWNERS` so their reviews will [automatically be requested](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) when relevant PRs are opened.
Notifications will be disabled as long as a PR is marked as "draft".
> CI: CODEOWNERS

- lib/google_maps_geocoder/google_maps_geocoder.rb
Expose the gem's logger so users can customize it.
1. Change `GoogleMapsGeocoder.new` to accept an optional `Logger`.
2. Default 1 to standard error.
3. Subclass `GeocodingError` from the more specific `RuntimeError`.
4. Pass logger to 3.
> f(x): GoogleMapsGeocoder.new accepts optional Logger

- README.md
- spec/lib/google_maps_geocoder_spec.rb
Fix the failures:
```ruby
Failures:
1) GoogleMapsGeocoder#new when API key is valid with "White House" is expected to be partial match
Failure/Error: it { is_expected.to be_partial_match }
expected `#<GoogleMapsGeocoder:0x0000000104619d88 @json={"results"=>[{"address_components"=>[{"long_name"=>"160...enue NW, Washington, DC 20500, USA", @formatted_street_address="1600 Pennsylvania Avenue Northwest">.partial_match?` to be truthy, got false
2) GoogleMapsGeocoder#new when API key is valid with "White House" is expected not to be exact match
Failure/Error: it { is_expected.not_to be_exact_match }
expected `#<GoogleMapsGeocoder:0x000000010848c110 @json={"results"=>[{"address_components"=>[{"long_name"=>"160...enue NW, Washington, DC 20500, USA", @formatted_street_address="1600 Pennsylvania …
```
> fix: match failures
