LICENSE.txt
README.md
google_maps_geocoder.gemspec

Bumped `activesupport` and `rack`.

Integrated Hakiri and fixed security warnings

---

lib/google_maps_geocoder/google_maps_geocoder.rb
spec/lib/google_maps_geocoder_spec.rb

Rename method names, arguments, and constants for clarity and relatedness.

Clearer method signatures

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
README.md
lib/google_maps_geocoder/google_maps_geocoder.rb

Update documentation.
1. Update copyright.
2. Remove deprecated Gemnasium badge.
1. Add inline documentation example.
2. Add emphasis for each step.
3. Remove line breaks to facilitate editing.

doc: updated github templates

---

google_maps_geocoder.gemspec
lib/google_maps_geocoder/version.rb

Bump to `0.6.0`.
1. Bump version.
2. Fix `gem build` warnings.

sys: bumped to 0.6.0

---

spec/lib/google_maps_geocoder_spec.rb

Fix spec.
Update context description to match test.

spec: fixed context

---

README.md
spec/lib/google_maps_geocoder_spec.rb

Fix failures.
1. Fix address-match failure.
2. Update copyright.

Fix failure and copyright

---

.github/workflows/publish.yml
.github/workflows/test.yml
README.md

Add a badge to reflect build status.
1. Rename workflows so badges conform to existing style.
2. Add badge to README.

Add testing badge

---

README.md

Add [BuyMeACoffee link](https://www.buymeacoffee.com/oblomov).

doc: added buymeacoffee link

---

SECURITY.md

Define a security policy.
Document:
1. supported versions.
2. how to report vulnerabilities.

doc: added SECURITY.md

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

Closes: #63
Attain silver-level CII Best Practices.
1. Add spec requirement to PR template.
2. Add link to docs.

CII silver: docs

---

CODE_OF_CONDUCT.md

Add a Code of Conduct.
Use [The Ruby Community Conduct Guideline](https://www.ruby-lang.org/en/conduct/).

doc: CODE_OF_CONDUCT.md

---

.github/PULL_REQUEST_TEMPLATE.md

Re: #63
Add RDoc example to PR template.

CII silver: added RDoc example

---

LICENSE.txt

doc: update copyright year in LICENSE.txt

---

.github/CONTRIBUTING.md
Gemfile

Closes: n/a
Improve security by using `https` wherever possible.
These were overlooked when Best Practices were initially passed.

CII Best Practices: https

---

.github/CONTRIBUTING.md

Re: #69
Document [two-person review](https://bestpractices.coreinfrastructure.org/en/projects/92?criteria_level=2#quality) process.

CII Gold: two-person review

---

.github/CONTRIBUTING.md
README.md
SECURITY.md
google_maps_geocoder.gemspec

Closes: n/a
Updated links to match new organization name.

refactor: renamed org

---

lib/google_maps_geocoder/version.rb

Bump to `0.7.6`
Shifting the release date to the beginning of the month rather than the ides.

conf: bumped to 0.7.6

---

LICENSE.txt
README.md
SECURITY.md

doc: updated copyright, version

---

SECURITY.md
lib/google_maps_geocoder/version.rb

conf: bumped

---

spec/lib/google_maps_geocoder_spec.rb

spec: cover #exact_match?

---

README.md

doc: highlight advantages

---

README.md

Document advantages with links.
(Self-explanatory)

doc: link advantages

---

.github/workflows/test.yml
README.md

Improve security by integrating OpenSSF's [Scorecard](https://scorecard.dev).
1. Add the [Scorecard action](https://github.com/ossf/scorecard-action?tab=readme-ov-file#authentication-with-fine-grained-pat-optional) to `test.yml`.
2. Add badge to README.

Integrate Scorecard

---

.github/workflows/scorecard.yml
.github/workflows/test.yml
README.md

fix: extract scorecard.yml

---

.github/workflows/scorecard.yml
.github/workflows/test.yml
README.md

Streamline workflow configurations for clarity.
1. Name Scorecard workflow "analysis" and its job "scorecard".
2. Remove `name` declarations so step calls are clear.
3. Fix badge.

Streamline workflows

---

.github/workflows/scorecard.yml
.github/workflows/test.yml
README.md

Improve security by integrating OpenSSF's [Scorecard](https://scorecard.dev).
1. Add `scoredcard.yml` using the [Scorecard](https://github.com/ossf/scorecard-action?tab=readme-ov-file#authentication-with-fine-grained-pat-optional) and [CodeQL upload-sarif](https://github.com/github/codeql-action?tab=readme-ov-file) actions.
2. Add badge to README.
3. To boost scorecard, update `test.yml` with:
a. default permissions
b. pinned action versions
c. DRYd step names

CI: scorecard
